### ISSUE TITLE
Need to hide window authentication popup for outside domain users

### ISSUE THREAD

**Issue by Pradeep24985** [MohammadYounes/MVC5-MixedAuth#26]
HI Mohammad,

Thanks for great solution. 

We are facing one issue in which when domain user make request to application it get successfully logged in but when request to comes from outside of domain it display "Window Credential" Popup window which required to cancel by user to allow application to redirect login page. 

Would it possible to remove/hide or bypass window credential window in case of non-domain user.

Thanks

**Comment by MohammadYounes** [comment]
The "Window Credential" prompt appears automatically when an unauthenticated user tries to access a windows protected resource, seems you have enabled windows authentication for the whole app and not just the windows login end point.

To enable windows authentication ONLY for the windows login end point, follow the steps mentioned [here](https://github.com/MohammadYounes/OWIN-MixedAuth#iis).

Does this help ?

**Comment by Pradeep24985** [comment]
Thanks for quick reply. 

still it showing popup for other user or when we access application using public IP. when ApplyChallenge() set statuscode =401 it display that popup window in browser.

Following things i have done in IIS:

> disabled windows authentication from default web site
> disabled windows authentication from application(i.e. MixedAuth)
> enabled windows authentication on Windows folder under MixedAuth application

Sample used https://github.com/MohammadYounes/MVC5-MixedAuth 

Thanks

**Comment by MohammadYounes** [comment]
`ApplyChallenge()` sets the status code only if `RequestChallenge()` was called, which in turn is only called inside `WindowsLoginHandler` process request.

So it seems to me that you are trying to access `http://app/Windows/Login` end point, and its windows protected, hence the prompt is shown!!

Are trying to disable the prompt from showing at all if the user is accessing this end point from a public IP ?

**Comment by Pradeep24985** [comment]
Yes, currently it is our requirement where internal user will automatically login with their credential and when any user try to access outside the domain network it should redirect to login page without windows credential prompt.

**Comment by MohammadYounes** [comment]
Then you should implement your own logic to make such decision [here](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Windows/WindowsLoginHandler.cs#L32), may be based on user IP.

**Comment by Pradeep24985** [comment]
Agreed, i am able identify public or private IP address now only thing is how i could suppress login prompt?

**Comment by MohammadYounes** [comment]
In this case no need for the windows login handler logic to execute, You should Redirect to login page and end the response!

**Comment by Pradeep24985** [comment]
In that case, will it automatically login for domain user in case of intranet ?

**Comment by MohammadYounes** [comment]
According to the above, in windows login handler, your custom logic goes:
1. Check user IP.
2. If external, redirect to login.
3. If internal, continue with the normal flow.

So Yes! but automatic login depends on client configuration, the app should be in an Internet Zone that has User Authentication set to Automatic.

![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)

**Comment by Pradeep24985** [comment]
Here is my requirement:
> when user open my application from domain network it should not ask login credentials ( it's working with your solution)
> when user open my application from outside of domain network like using datacard or without VPN, it should redirect user to login page(it's working but only thing is login prompt by browser that required to be cancel by user)

it would be good if you could something to avoid login prompt.

**Comment by MohammadYounes** [comment]
Did you implement the redirect ? it should be before `RequestChallenge` call!

**Comment by Pradeep24985** [comment]
I have made few changes as you suggested in https://github.com/MohammadYounes/MVC5-MixedAuth/issues/6 for auto window login. 

apart from this, i didn't made any changes but would like to add if user is "Unauthorized" in case of out of domain network and redirecting to login page it should not show "Window Login Prompt" in browser

**Comment by MohammadYounes** [comment]
On second thought, I think you should make your update [here](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Windows/MixedAuthExtensions.cs#L68-L75), such as:

```C#
/// <summary>
/// Invoke on end response only. Replaces the current response status code with 401.2
/// </summary>
/// <param name="context"></param>
public static void ApplyChallenge(this HttpContext context)
{
    bool isInternal = myCustomCheckLogic();

    if (context.Response.StatusCode == fakeStatusCode)
    {

        if (isInternal)
        {
            context.Response.StatusCode = 401;
            context.Response.SubStatusCode = 2;
        }
        else 
        {
            context.Response.StatusCode = 302;
            context.Response.RedirectLocation = "/Login";
        }
    }
}
```

**Comment by Pradeep24985** [comment]
Great, will check and update you once done :)

**Comment by Pradeep24985** [comment]
It worked, Thanks for quick response. really appreciated

The only i am looking pending is when we use application from public IP in our domain it didn't take window credentials of mine.

**Comment by MohammadYounes** [comment]
Great! did you provide full domain name when trying to sign in ?

**Comment by Pradeep24985** [comment]
Yes, basically when domain user open application using public IP it prompt
login window. To over come  from this issue, i made changes in IE setting
User Authentication -> Enabled Automatic log-on with current username and
password.

**Comment by MohammadYounes** [comment]
Glad it worked out! If the repo was helpful to you, give it a star :)
