### ISSUE TITLE
How would you go about initiating BeginWindowsAuthForm in code?

### ISSUE THREAD

**Issue by kkfrosty** [MohammadYounes/MVC5-MixedAuth#28]
We're exploring this sample for use in our application.  However, we want the application somewhere on initialization to get a windows user if available and then validate it in code.

Basically I'm trying to figure out how to simulate what happens when a user clicks on the Windows button.

**Comment by MohammadYounes** [comment]
Clicking the windows button makes a post that will be handled by the [WindowsLoginHandler](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Windows/WindowsLoginHandler.cs), The code flow is described [here](https://github.com/MohammadYounes/MVC5-MixedAuth#flowchart-of-the-windows-login--link-code-flow-contributed-by-combofusion).

**Comment by kkfrosty** [comment]
I understand how it currently works.  But in an environment where you want to use Windows Authentication, you shouldn't take a user to a login page and make them click a button to authenticate.  The point of integrated windows authentication, a user opens an application and they are automatically authenticated.

So thus, the question, I'm trying to figure out how to get the functionality out of this sample programmatically.  The application loads and everything that happens when the Windows button is clicked takes place behind the scenes without a user doing anything.

**Comment by MohammadYounes** [comment]
This is a mixed authentication, not windows only! Did you see [this issue](https://github.com/MohammadYounes/MVC5-MixedAuth/issues/6) ?

**Comment by MohammadYounes** [comment]
The solution is implemented in [Windows First branch](https://github.com/MohammadYounes/MVC5-MixedAuth/tree/WindowsFirst)

**Comment by kkfrosty** [comment]
I didn't not find that issue.  Sounds exactly what we're looking for.  Thank you much.  I'll close this for now and revisit if I have questions.  Thanks.

**Comment by kkfrosty** [comment]
FYI.  I have to engage in another task.  FYI.  The sample link you set does not work as is.  It loads the Index page but no authentication takes place.  It needs an authorize for the HomeController Index action.
However, in doing that there is no /windows/Login route.  A 404 File or directory not found is returned.  I'll try to get back to this in the morning

**Comment by MohammadYounes** [comment]
Yes! it was intended this way. About/Contact links requires logging in, as for the 404 you may need to adjust the path in case you did run this as an application instead of a website.
