### ISSUE TITLE
The code in Startup.cs isn't getting called

### ISSUE THREAD

**Issue by pixievinayak** [MohammadYounes/MVC5-MixedAuth#30]
Hi Mohammad,

My ultimate aim is to achieve Auto Windows Login, and I have followed the steps you have mentioned in #6, but nothing happened. Upon investigating further, I realized that the original redirect to /Account/Login itself wan't happening and that the code inside Startup.cs isn't getting called at all.

I am using the Update 3 Branch code. (I originally tried this with the master branch code but with no luck there too)

Please help.

**Comment by pixievinayak** [comment]
I have also tried this with the WindowsFirst branch code. But here too the code inside Startup.cs isn't getting called.

I really don't know how to proceed. 

Please do help.

**Comment by MohammadYounes** [comment]
Have you tried running the WindowsFirst branch itself or you added it's code to an existing project? If its the later, can you share the code to be able to debug ?

**Comment by pixievinayak** [comment]
I tried running the code from the windows branch itself.
It goes to the home page on start-up.
I'm using Visual Studio 2013, iis 8.5 and SQL express 2012 on a Windows 8.1
system.
Everything works fine, except for the windows first login.

**Comment by MohammadYounes** [comment]
Are you running Windows 8.1 or Windows 8.1 Pro ?

**Comment by pixievinayak** [comment]
I'm using Windows 8.1 Pro.

**Comment by MohammadYounes** [comment]
I tried this on a Windows 8.1 Pro and it works as expected! The home page is set to allow anonymous access and thus no registration is required, when you go to About or Contact pages, the current windows user will be automatically registered or signed in. If no credentials were passed, the app will redirect you to login page.

**Comment by pixievinayak** [comment]
I understand that, but my issue is that by default the application does not ask for my Windows credentials.

Just for my understanding, what is changing the LoginPath in Startup.Auth.cs from "/Account/Login" to "/Windows/Login" supposed to do?

As per my understanding with the WindowsFirst approach is that when you navigate to the url "http://[server]/MixedAuth", the application should ask for my windows credentials and then do whatever it does. This isn't happening. It's taking me directly to the Home/Index page. Everything else in the application is working fine.

If my understanding is incorrect I guess I've misunderstood and I'm sorry.

**Comment by MohammadYounes** [comment]
Just add authorize attribute to the Home/Index action and you'll be asked for credentials.

**Comment by MohammadYounes** [comment]
The LoginPath is used to redirect the user when a request to a protected resource is made, the home page ([Index Action](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/WindowsFirst/src/Controllers/HomeController.cs#L11)) does not require authorization!

On the other hand [About/Contact Actions](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/WindowsFirst/src/Controllers/HomeController.cs#L16-L29) are protected and do require authorization, accessing them will redirect you to `/Windows/Login` and if authentication fails! you'll be redirected to `401.html` which contains a meta refresh that will send you to `/MixedAuth/Account/Login`.

If accessing About/Contact actions does not prompt you for username/password, then you might want to check your internet settings and the zone in which your application resides:

![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)

**Comment by pixievinayak** [comment]
Aah!! Now everything is clear. Thank you SO SO much Mohammad.
