### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by nohwnd** [MohammadYounes/MVC5-MixedAuth#31]
Thanks for this solution, that's super-clever. Did you came up with it yourself or, did you follow some tutorial? :)

**Comment by MohammadYounes** [comment]
This was my first attempt in solving this for ASP.NET MVC, Before MVC I was using this [approach](https://msdn.microsoft.com/en-us/library/ms972958.aspx). 

Now I use [OWIN-MixedAuth](https://github.com/MohammadYounes/OWIN-MixedAuth).

Thanks :)
