### ISSUE TITLE
Works in IIS Express but not when deployed in localhost

### ISSUE THREAD

**Issue by sohelm1** [MohammadYounes/MVC5-MixedAuth#32]
First of all great article!!! I just tried your sample and it works great when i run under iis express. But when I run under local IIS (version 7.5) i get the following error:

HTTP Error 401.2 - Unauthorized
You are not authorized to view this page due to invalid authentication headers.
Detailed Error Information
Module	global.asax
Notification	EndRequest
Handler	Windows Login Handler
Error Code	0x00000000
Requested URL	http://localhost:80/MixedAuth/Windows/Login
Physical Path	C:\DEV\ePOWER90\OWIN\MVC5-MixedAuth-master\MVC5-MixedAuth-master\src\Windows\Login
Logon Method	Anonymous
Logon User	Anonymous

The authentication settings of the virtual directory has Anonymous enabled and Windows Authentication enabled.  Could help me with this please?

**Comment by MohammadYounes** [comment]
Seems you are not authenticating, please check the internet options settings and make sure it's not set to anonymous :

![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)

**Comment by sohelm1** [comment]
Thanks for the prompt reply. My internet settings are already set as you have proposed.

**Comment by MohammadYounes** [comment]
How did you deploy the project - as website or a web application ? If it's the later, please confirm that you have enabled windows authentication on the application level (not just the website level).

**Comment by sohelm1** [comment]
Ok. I feel like a fool now. I did enable windows authentication but i did it for the wrong application, thinking that was the one i was working with. This is what happens when you work on multiple things at the same time. The good news is after configuring the "correct" application, everything is working as expected.

Thanks so very much for taking the time to help me through this. Also many thanks for putting up the very useful article in the first place.

**Comment by MohammadYounes** [comment]
no worries :)
