### ISSUE TITLE
HTTP 404 on /Windows/Login after deploying to IIS

### ISSUE THREAD

**Issue by emf411** [MohammadYounes/MVC5-MixedAuth#33]
I hope that this question hasn't been answered somewhere else, but I'm having an issue with the getting the WindowsFirst branch to work.

First off, this is a terrific solution and is exactly what I was looking for!  Implementation so far has gone very smooth except for 1 glitch.

I am a local user on the domain so I would expect to be automatically logged in and brought to my HomeController.  I've gotten my project working locally in my development environment , my Startup.Auth.cs is pointing to "/Windows/Login".  From IIS Express it works as expected, I am automatically logged in and get to the Home page.

However, after deploying my site to IIS 7.5 (on a Windows 2008 server on the local network) and try to pull up the site, I'm receiving the following error:

Server Error in '/' Application.
--------------------------------------------------------------------------------

The resource cannot be found. 
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /Windows/Login

--------------------------------------------------------------------------------
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249 

If I remove the "Windows/Login?ReturnUrl=%2F" from the query string and try to load the page two times in a row, it will allow me to get to my HomeController (which has [Authorize] enabled).

Is there some type of custom 404 handler that I might need to this scenario that you can help me with implementing?

Thank you very much!

**Comment by MohammadYounes** [comment]
I wasn't able to reproduce the described error! Are you using the WindowsFirst branch as is ? or did you make some adjustments ?

**Comment by emf411** [comment]
Thank you for testing!  I am adding the WindowsFirst branch to an existing project so some adjustments were made.  Something must have broken during my implementation.

I have actually switched over to use your OWIN-MixedAuth project which has gotten me almost to where I need to be.

Thanks for your help!
