### ISSUE TITLE
Authorizing Windows user instead of linking account.

### ISSUE THREAD

**Issue by engenb** [MohammadYounes/MVC5-MixedAuth#34]
Heyo

This project appears to be exactly what I need, however I have no forms authentication in my application in contrast to your examples.

### What I'm doing ###
I have a website that uses windows authentication, mobile clients that use webapi token-based oauth security, and an integration api that uses a simliar api-key token-based security.  The windows users accounts exist in a database which I need to query to check that the authenticated windows user has access to the application.  This is preferred over using AD groups in Authorize attributes.

I'm considering splitting some of these back-end concerns up, but for now they're all serviced by one web server

### Where I'm at ###
If request isn't successfully authenticated through the Owin pipeline, I get redirected to the virtual endpoint /Windows/Login, which seems to be where the WindowsLoginHandler comes into play.  The flow works, triggering a 401 challenge.  On successful authentication, I'm sent back through the WindowsLoginHandler.  I have an authenticated LoginUserIdentity, but my session doesn't have a userId yet so I'm sent through WinLoginAsync which appears to be attempting to redirect to my Account/WindowsLogin endpoint.

Your flow here redirects them to a login form.  I need to auto log them in if their account exists in my db.  I'm attempting to just do this work in AccountController.Windows' WindowsLogin endpoint, but I never get there.

### What I'm asking ###
I guess I'm wondering if this could be done in a simpler fashion since I don't need to redirect my users to login forms.  Or, do you have any thoughts why ExecuteController may not be hitting my endpoint?

Thanks!

**Comment by MohammadYounes** [comment]
Hi,

The redirect to login form occurs only if `LogonUserIdentity` is not [authenticated](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.Windows.cs#L33-L36), But you say:

>On successful authentication, I'm sent back through the WindowsLoginHandler. I have an authenticated LoginUserIdentity, but my session doesn't have a userId yet so I'm sent through WinLoginAsync

So you are hitting [this line](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Windows/WindowsLoginHandler.cs#L63), which will execute `WindowsLogin` action, correct ?

But again you say:
>Your flow here redirects them to a login form. I need to auto log them in if their account exists in my db. 


So how is it that you are redirected to login form, as you should hit [this line](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.Windows.cs#L38). which passed the point of redirecting to the login form ?

**Comment by engenb** [comment]
I may not have described correctly what is happening.  The good news is, I resolved my issue.  Since I'm redirecting to a login endpoint and not posting to one from a login form, I shouldn't have a ValidateAntiForgeryToken attribute on my endpoint.  It's working great now!

Thanks!

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
