### ISSUE TITLE
 to authenticate request user

### ISSUE THREAD

**Issue by kamranbashir** [MohammadYounes/MVC5-MixedAuth#37]
```C#
public async Task<ActionResult> WindowsLogin(string userName, string returnUrl)
{
      // can we call hander from MVC action, to authenticate request user?		
      var handler = new WindowsLoginHandler();
      var processAwait = await   handler.ProcessRequestAsync(System.Web.HttpContext.Current);
}
```

**Comment by MohammadYounes** [comment]
The question is unclear, can you explain?

**Comment by kamranbashir** [comment]
salam alikum

Rather than having http handler set-up, can we pass System.Web.HttpContext.Current as httpcontext
 to  a method ProcessRequestAsync(System.Web.HttpContext.Current) of class WindowsLoginHandler from MVC controller method?

the objective is to get Request.logonUserIdentity.IsAuthenticated to make it true.
which will help us in order to pass successful credential to identity for signin purpose

thanks,
kamran

**Comment by MohammadYounes** [comment]
walaikum assalam

May be! but this is a multi-step process. I recommend switching to [OWIN-MixedAuth](https://github.com/MohammadYounes/OWIN-MixedAuth), in which you can simply request a windows login by:

``` C#
[AllowAnonymous]
public ActionResult WindowsLogin(string returnUrl)
{
    return new ChallengeResult("Windows",
              Url.Action("ExternalLoginCallback", "Account",new { ReturnUrl = returnUrl }));
}
```

Thanks!

**Comment by kamranbashir** [comment]
salam
i tried , it did not work. 
only i can see it bring a pop up to enter user and password.
which i do not want.
can u pls give me a working solution.
JazkAllah khair

**Comment by MohammadYounes** [comment]
Not sure I understand your goal, Join me here http://gitter.im/MohammadYounes/OWIN-MixedAuth

**Comment by kamranbashir** [comment]
Salam,
how to perform group validation in mvc 5? any idea

**Comment by kamranbashir** [comment]
Here are some scenario requirements, might you could advise me using MVC%
• Only one form to make post
• One model will contain ID, NAME, ADDRESS, OLDPASSWORD, NEWPASSWORD, CONFIRM PASSWORD.
• There will be two sets for separate / group validation / rule set
• Set 1: ID, NAME, ADDRESS
• Set 2: OLDPASSWORD, NEWPASSWORD, CONFIRM
• The Form will contain two buttons
• Button 1: Save profile 
• Button 2: Save password
Button1 will validate set1 and button 2 will validate set 2

Can we achieve this using one form? Or we have to place this in two form.
Ideally I am looking to implement in one form.
If you could advise better, please do so.

Thanks,

**Comment by MohammadYounes** [comment]
Walaikum assalam,

You can simply include a hidden field to indicate the action, Button1 will validate the first group and set the hidden field value to "profile" then submits the form. Button2 will validate the second group and set the hidden field value to "pass" then submits the form. Your controller performs the required action based on the hidden field value.

Or 

You can have two controller actions, one for each set. Each button updates the form `action` value  before submitting.

**Comment by kamranbashir** [comment]
Morning,
here is a class
public class MyClass {
//Group A
  public string Id { get; set; }
  public string Name { get; set; }
  public string Address { get; set; }
//Group B
  public string OldPassword { get; set; }
  public string NewPassword {get;set;}
  public string ConfirmPassword {get;set;}
}


For instance, this is our tiny model. How we can do.
Can u give some working sample chtml and c# code?

Wsalam
Kamran

**Comment by MohammadYounes** [comment]
Hello, 

This is off topic, and with a bit of googling you can find many solutions online. For example: http://www.codeproject.com/Articles/315540/Announcing-MVC-Validation-Groups

Thanks!

**Comment by kamranbashir** [comment]
I think group validation never exists after MVC3.only till MVC3 we had [ValidationGroup] attribute available.
u have to split your model in groups and then for each group u have make separate form.

I understand it is off topic, but some time u can ask someone expert for their experience or suggestion.
anyways  thanks for help.

Jazakak Allah Khair

**Comment by MohammadYounes** [comment]
Sure thing! but this is not the right place :)

Moreover, Validation Groups never existed in MVC, not even MVC3. The link I shared is a custom implementation to mimic the Web Forms validation groups behavior. 

Thanks!

**Comment by kamranbashir** [comment]
Salam,
I hope you are well, I thought take some suggestion in applying AD authentication. 
I am able to do it using web.config , window users (non-AD) have to fill windows login dialog.
<authorization>
  <allow roles="BT\Domain Users" />
  <deny users="*" />
</authorization>

So everything goes fine till point. But seems i am not signed in by identity. when i try to get HttpContext.Current.User.Identity.GetUserId(), i get null!!!!

protected void Application_PostAuthenticateRequest(object sender, EventArgs e)
 {

   if (HttpContext.Current.User.Identity.IsAuthenticated)
     {
     var user = _repo.FindBy(u => u.UserName == 'BT\Kam');
     var roleName = ((UserRoles)role.RoleId).ToString().Replace("_", " ");
     var u = new System.Security.Principal.GenericIdentity(context.User.Identity.Name, "Windows");
     u.AddClaim(new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.NameIdentifier, user.Id.ToString()));
     u.AddClaim(new System.Security.Claims.Claim("fullname", string.Format("{0} {1}", user.FirstName, user.LastName)));
     string[] roles = new[] { roleName };
     var newUser = new System.Security.Principal.GenericPrincipal(u, roles);
     System.Threading.Thread.CurrentPrincipal = newUser;                        
      }
     else
     {
     //redirect to error page
     }
}

could u help or advise how to make sign in? so i could get user id using  HttpContext.Current.User.Identity.GetUserId().
if i do normal login i do get user Id.

Thanks,

**Comment by MohammadYounes** [comment]
Salam,

You need is to sign the user in using `AuthenticationManager`, similar to [AccountController](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.cs#L334-L339):

```C#
private async Task SignInAsync(ApplicationUser user, bool isPersistent)
{
  AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
  var identity = await UserManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
  AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = isPersistent }, identity);
}
```
Thanks!

**Comment by kamranbashir** [comment]
but i am at application level. are u sure i will be able to access SignInAsync in below method:
protected void Application_PostAuthenticateRequest(object sender, EventArgs e)
 {}

thanks,

**Comment by MohammadYounes** [comment]
I'm not sure what exactly are you doing! I just pointed out the code responsible for creating the cookie, the authentication manager is retrieved from the [OWIN context](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.cs#L326-L332). Then it's used to sign the user in (You already have the user!).

What do you mean by access the `SignInAsync` method ?

**Comment by kamranbashir** [comment]
i sent u code. i thought u will understand i am not in controllers
i am at application events level.
thanks

**Comment by kamranbashir** [comment]
for example i cannot get usermanager in application events level.
HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

thanks,

**Comment by MohammadYounes** [comment]
I got you are not in controllers and I sent you pointers of what needed to be done to sign the user in! 

Why do you need UserManager ? you already have the `_repo` !!

**Comment by MohammadYounes** [comment]
I'm not sure if the authentication manager is available during post authenticate or not, bu you may try this:

```c#
protected void Application_PostAuthenticateRequest(object sender, EventArgs e)
{

    if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        var user = _repo.FindBy(u => u.UserName == 'BT\Kam');
        var roleName = ((UserRoles)role.RoleId).ToString().Replace("_", " ");
        var u = new System.Security.Principal.GenericIdentity(context.User.Identity.Name, "Windows");
        u.AddClaim(new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.NameIdentifier, user.Id.ToString()));
        u.AddClaim(new System.Security.Claims.Claim("fullname", string.Format("{0} {1}", user.FirstName, user.LastName)));
        string[] roles = new[] { roleName };
        // SignIn
        IAuthenticationManager AuthenticationManager = HttpContext.GetOwinContext().Authentication;
        AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
        var identity = await UserManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
        AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = isPersistent }, identity);
    }
    else
    {
        //redirect to error page
    }
}
```

**Comment by kamranbashir** [comment]
ok i try

**Comment by kamranbashir** [comment]
out of abouve four lines , this line i am unable to reslove
   var identity = await UserManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie); 

event i tried like this
  var um= HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
GetUserManager doest not exist

**Comment by MohammadYounes** [comment]
Replace it with your own logic to create the identity, see [this comment](https://github.com/MohammadYounes/MVC5-MixedAuth/issues/20#issuecomment-58816668)

**Comment by kamranbashir** [comment]
public static class OwinHelper
{
    public static ClaimsIdentity CreateIdentity(ApplicationUser user, string authenticationType)
    {
        var claims = new List<Claim>
    {        
        new Claim(ClaimTypes.Email, user.Email, null, ClaimsIdentity.DefaultIssuer, "Provider"),
        new Claim("fullname", string.Format("{0} {1}", user.FirstName, user.LastName, "Provider"))
    };

        return new ClaimsIdentity(claims, authenticationType);
    }
}

**Comment by kamranbashir** [comment]
IAuthenticationManager AuthenticationManager = HttpContext.Current.GetOwinContext().Authentication;
                        AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
                        var identity = OwinHelper.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);
                        AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, identity);

**Comment by kamranbashir** [comment]
code has not error, but does not work signin...
thanks

**Comment by MohammadYounes** [comment]
I recommend using [OWIN-MixedAuth], because its modular and works seamlessly with other authentication providers.

Thanks!

**Comment by kamranbashir** [comment]
shorter version
 var identity= new System.Security.Principal.GenericIdentity(context.User.Identity.Name, "Windows");
                        identity.AddClaim(new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.NameIdentifier, user.Id.ToString()));
                        identity.AddClaim(new System.Security.Claims.Claim("fullname", string.Format("{0} {1}", user.FirstName, user.LastName)));
                        string[] roles = new[] { roleName };
                        var newUser = new System.Security.Principal.GenericPrincipal(identity, roles);
                        System.Threading.Thread.CurrentPrincipal = newUser;
                        context.User = System.Threading.Thread.CurrentPrincipal = newUser;
                        IAuthenticationManager AuthenticationManager = HttpContext.Current.GetOwinContext().Authentication;
                        // AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);                       
                        AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, identity);


surprisingly! now i get windows  authentication required dialog

**Comment by kamranbashir** [comment]
HttpContext.Current.User.Identity.IsAuthenticated is true
but after running above block i get windows authentication required dialog.
is my calim is not vaild? of may be some thing else.

if u can suggest any thing that is good.
other wise i can stop here

Thanks,

**Comment by MohammadYounes** [comment]
Share a sample project with your custom logic so I can test/debug.

Thanks!

**Comment by kamranbashir** [comment]
i wish i could i am in office area...
correction, because of below line, windows authentication dialog was appearing
context.User = System.Threading.Thread.CurrentPrincipal = newUser;

removed not required line...
ok now situation is that we are not still able to sign in, code has no error

**Comment by kamranbashir** [comment]
HttpContext.Current.User.Identity.GetUserName() return null

but

after doing this    System.Threading.Thread.CurrentPrincipal = principal;
System.Threading.Thread.CurrentPrincipal.Identity.GetUserName() return id

it seems like sign-in is successful !!!!
but u cannot get desired from HttpContext.Current.User.Identity
have to use System.Threading.Thread.CurrentPrincipal.Identity

is that normal?

**Comment by MohammadYounes** [comment]
Yes, because they are different properties

**Comment by kamranbashir** [comment]
it is working now :)
var newUser = new System.Security.Principal.GenericPrincipal(identity, roles);
Thread.CurrentPrincipal = newUser;  
 every where i am using Thread.CurrentPrincipal 
e.g .. Thread.CurrentPrincipal.Identity.GetUserId()

**Comment by MohammadYounes** [comment]
Are you sure this will be applied to all threads? What if a different thread served the request ?

**Comment by kamranbashir** [comment]
opps i did not know that.
how we can overcome this?

**Comment by MohammadYounes** [comment]
It's your solution, figure it out :)

**Comment by kamranbashir** [comment]
ok mate

**Comment by kamranbashir** [comment]
I wanted to one question
I have two scenarios
1.First it is windows user but not active directory user. I get **windows authentication** popup.
2.If user is active directory user but not validate against database then I set HttpContext.Current.User=null and I get **windows authentication** popup.

**How to hide or not show this popup**? just send to an error page
Error message 401.2.: Unauthorized: Logon failed due to server configuration

thanks,

**Comment by MohammadYounes** [comment]
See #26

**Comment by kamranbashir** [comment]
great, i will confirm u 

JazakAllah khair
