### ISSUE TITLE
Automatic windows  Authentication

### ISSUE THREAD

**Issue by DespeiL** [MohammadYounes/MVC5-MixedAuth#39]
Hi Mohammad . At first thank you for your fantastic mix  Authentication system , it works fine and  save time of my time. But is there any way to skip windows authentication window and use current user data?

**Comment by MohammadYounes** [comment]
Hi,

Automatic login depends on client configuration, the web app should be in an **Internet Zone** that has **User Authentication** set to **Automatic**.

![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)

**Comment by DespeiL** [comment]
I have the same settings as in screenshot but still when i first time enter my site it's asking me for User name and Passwors
![przechwytywanie](https://cloud.githubusercontent.com/assets/12883690/14497414/35897a32-0197-11e6-9a28-71001e7c0b0f.JPG)

**Comment by MohammadYounes** [comment]
Is your site a member of "**Local Intranet Zone**" ?

![intranet](https://cloud.githubusercontent.com/assets/4712046/14497618/121b74b6-01a0-11e6-94fd-fd3304e7abe0.png)
![intranet-zone](https://cloud.githubusercontent.com/assets/4712046/14497619/121d8ce2-01a0-11e6-9abb-c6f089550f02.png)

**Comment by DespeiL** [comment]
Thx, in IE it works fine . But still I need fix redirect  after cancel button press , it's possible ?

**Comment by MohammadYounes** [comment]
Yes,  Add a custom error page configuration, as described [here](https://github.com/MohammadYounes/MVC5-MixedAuth/issues/5#issuecomment-41413348). Then you can either customize the 401.html to display some informative message or redirect users to the normal Login action:
```HTML
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <meta http-equiv="refresh" content="0;URL='/MixedAuth/Account/Login'" />    
</head>
<body>
  Invalid credentials 
</body>
</html>
```

**Comment by DespeiL** [comment]
Already did this but after Cancel click it's redirect me to Windows/Login  .Even when I change LoginPath in  Startup.Auth  to something else it's still redirect to Windows/Login

**Comment by MohammadYounes** [comment]
Why would it redirect you to Windows/Login ? Try to re-check your configuration.

**Comment by MohammadYounes** [comment]
I retested the [WindowsFirst] branch, and it works as expected. Make sure you 

1. Update `LoginPath` in **Startup.Auth**  `LoginPath = new PathString("/Windows/Login")`
2. Make `401.html` redirect to normal login page `<meta http-equiv="refresh" content="0;URL='/Account/Login'" />` and that login page does not require authorization.

You do need to re-check your configuration :smile:

**Comment by DespeiL** [comment]
Solved.
 Some 'genius' from my team comment `context.Response.TrySkipIisCustomErrors = true`:sweat_smile:

I have one more problem. Since automatic windows authentication  not work in Edge ,Firefox and maybe some others brothers , in them user should enter his User Name and Password and 
when he login with windows user account it's impossible to login into other windows account.

So is there any way to make complete LogOff ?

**Comment by MohammadYounes** [comment]
You need to either close the browser or invalidate the browser credentials cache. see  http://signinas.codeplex.com
