### ISSUE TITLE
WindowsAuth 404 on IIS 8.0

### ISSUE THREAD

**Issue by DespeiL** [MohammadYounes/MVC5-MixedAuth#42]
On my IIS express everything works fine but after publishing my application on IIS8 server i have 404 when try to login with windows authentication while login authentication  works normal.

I should change something in code , or in IIS 8.0 settings?

**Comment by MohammadYounes** [comment]
It's hard to tell with the amount of info you provided, Have you checked the other [404 related issues](https://github.com/MohammadYounes/MVC5-MixedAuth/issues?utf8=%E2%9C%93&q=is%3Aissue+404) ?

Moreover, 

* Which branch are you using ?
* Are you using the default project found in this repo, or you have your own modified version ?
* Is it deployed as an application or a website ?

Thanks!

**Comment by DespeiL** [comment]
- master 

-  modification:

1.  https://github.com/MohammadYounes/MVC5-MixedAuth/issues/6#issuecomment-44013012 (commented on 23 May 2014)
2. https://github.com/MohammadYounes/MVC5-MixedAuth/issues/39

- don't understand this question

**Comment by MohammadYounes** [comment]
Seems you deployed it as an application named `MySite`. In this case just update the meta refresh to account for the App name:
```html
  <meta http-equiv="refresh" content="0;URL='/MySite/Account/Login'" />    
```

**Comment by DespeiL** [comment]
Yea, you right. I checked everything except this.

However it seems that there is 401 error because windows authentication not work.

Any suggestions why it's not working on ISS8 but ok on Express?

**Comment by MohammadYounes** [comment]
Is it enabled? please confirm that you have enabled windows authentication on the application level (not just the website level).

**Comment by DespeiL** [comment]
If you are talking about project property "Windows Authentication" than, yes it's enabled.

As I said everything works fine in default  ISS Express

**Comment by MohammadYounes** [comment]
Nop, I'm talking about IIS configuration see https://github.com/MohammadYounes/MVC5-MixedAuth/issues/9#issuecomment-45714546

**Comment by DespeiL** [comment]
Turn it on. But still 401

**Comment by MohammadYounes** [comment]
On application level? not just website level.

**Comment by DespeiL** [comment]
As it shown in #9 (comment)

**Comment by MohammadYounes** [comment]
Hmm, What about https://github.com/MohammadYounes/MVC5-MixedAuth/issues/39#issuecomment-209830210 ?

**Comment by DespeiL** [comment]
Solved 

Was bug on server , after saving setting they were restart to default , after fixing this and again set settings as shown in  #9 (comment) everything works fine.

Thx for your time and help.

**Comment by MohammadYounes** [comment]
Great, Thanks for the feedback!
