### ISSUE TITLE
can't catch WindowsLoginHandler

### ISSUE THREAD

**Issue by MohammadHijazi** [MohammadYounes/MVC5-MixedAuth#43]
I applied the sample exactly at my project but when I press windows button to login it gives 
windows/login
 HTTP Error 404.0 - Not Found
I am using local iis 
and 
when I debug the code it does not catch the CreateRouteData at MixedAuthExtensions

![iis](https://cloud.githubusercontent.com/assets/20769786/17290592/e99a95aa-57e7-11e6-8daf-5607571bfa2d.png)
![webconfig](https://cloud.githubusercontent.com/assets/20769786/17290591/e998be4c-57e7-11e6-9b32-dfb8dbe8acbe.png)

**Comment by MohammadYounes** [comment]
You must be missing something! How do you access the handler URL, The handler registration indicates it only accepts POST verb.

**Comment by MohammadYounes** [comment]
Also take a look at this [comparison](https://github.com/MohammadYounes/MVC5-MixedAuth/compare/0544d70937035c6d220520c76c4e3a7df20afe28...Update3) which compares a new MVC project to a Mixed-Auth project. Might help you spot what's missing!

**Comment by MohammadHijazi** [comment]
thanks for your replay , yes I solved it , by mistake the location of handler at web.config was wrong.

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
