### ISSUE TITLE
Custom check for windows authintication 

### ISSUE THREAD

**Issue by MohammadHijazi** [MohammadYounes/MVC5-MixedAuth#44]
dear,
I want the place to get the current user identity and check if this user exist at my SQL database, if yes I want to prepare the claims at identity and if not I want to redirect to login page.

so where I must check this before redirect to login page , it always redirect me to login page

I appreciate your support

**Comment by MohammadYounes** [comment]
At the [`WindowsLogin`](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.Windows.cs#L31) action, This [line](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.Windows.cs#L41) is where the windows identity is matched against the database.

**Comment by MohammadHijazi** [comment]
Thanks for you fast respond,
according to the windowsLogin action, i search at my sql by UserName , but at i can't get the username because the anonymous authentication ,, how i can get the username of login user , any advice please   
i tried to use 
Thread.CurrentPrincipal.Identity.Name
but it empty

**Comment by MohammadYounes** [comment]
The [`LogonUserIdentity`](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/Controllers/AccountController.Windows.cs#L33) holds the windows identity.

**Comment by andersonfluz** [comment]
@MohammadYounes how are you? 
I read the question of @MohammadHijazi and testing your project and i implemented the LogonUserIndentity in my project and it's worked!  but when i published in production server the LogonUserIdentity get the User of Server. you saw this error?

**Comment by MohammadHijazi** [comment]
Dear,
thank for your support and your effort to help us.

as i told you i want to do windows authentication from my sql server by username and if not exist i will redirect to form authentication.
i used LogonUserIdentity to get username.
and i did some custom code to check the authentication as the following:

![winlogin](https://cloud.githubusercontent.com/assets/20769786/17356579/f49965e2-5960-11e6-8652-84804a26acfe.png)

note that i sent my custom user to the SignInAsync 

and at the SignInAsync  i get the claims of the user from my database and it tried to add them to the ClaimsPrincipal as the following

![signin](https://cloud.githubusercontent.com/assets/20769786/17356904/a7fb4258-5962-11e6-8f05-f805431856dd.png)

"i did all these customizing because i need to use my custom database user and claim schema"

but after all that user does not  granted the authentication and it keep him to the login page

as the following:
![handller](https://cloud.githubusercontent.com/assets/20769786/17357195/396f67cc-5964-11e6-8ec0-b1a125a7ac50.png)

any advice ?

**Comment by MohammadYounes** [comment]
@andersonfluz What do you mean by the User of Server? Is it IUSER account ?

@MohammadHijazi You are not associating the correct `AuthenticationType` with the created identity, It should match the [`CookieAuthenticationOptions`](https://github.com/MohammadYounes/MVC5-MixedAuth/blob/master/src/App_Start/Startup.Auth.cs#L16).


May I ask why not to use [OWIN-MixedAuth](https://github.com/MohammadYounes/OWIN-MixedAuth) ?

**Comment by MohammadYounes** [comment]
Closing ... Feel free to post if you still have further questions!

**Comment by nityadao** [comment]
I have 3 types of login provider.(Forms, Windows & Mixed).

When I set form authentication then only form login page display (windows login button not display).
when I set None then Mixed mode work.
when I set windows then default windows login works, but its not add any data to user table of identity. 
but in windows authentication (button click) of mixed mode its works.

How to add data in identity table for only windows authentication user.

thanks

**Comment by MohammadYounes** [comment]
You can't. As the identity system is based on a local user connected to multiple identities. 

All you can do is have the local accounts without passwords (null password), so users will not be able to login using them.

Hope this helps!

**Comment by nityadao** [comment]
There is any technique to skip the default windows authentication and apply custom login code to valid and add new user data but without opening login forms. 

Thanks for quick reply.

**Comment by MohammadYounes** [comment]
@nityadao You can use directory services to import Windows users, when you add a login to user logins table the provider should be Windows and the Key should be the users SID.
