### ISSUE TITLE
WindowsFirst solution not working?

### ISSUE THREAD

**Issue by rajparmar** [MohammadYounes/MVC5-MixedAuth#47]
Hi Mohammed, I've downloaded the WindowsFirst branch and followed your instructions to run it but I am unable to do so. I'm using Visual Studio 2015 and enabled Windows Authentication in IIS Express but it results in a 500 error on start up. I can't seem to find where the error is occuring, After hitting breakpoints it the Global.asax.cs and Startup.cs, it just fails.

Are you able to replicate this?

**Comment by rajparmar** [comment]
Ok please ignore my last question. After some sleep and coffee, I realised I had added authentication settings into the web.config which IIS Express didn't like. I removed this and it all started working.

**Comment by MohammadYounes** [comment]
Thanks for the feedback :)
