### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by softestpk** [MohammadYounes/MVC5-MixedAuth#48]
Hey, I am using chrome for mixed auth testing. When I use window authentication, it authenticates it fine. But when I logout and login again, it does not ask username /password. There is no 401 challenge. How to force a 401 challenge on logout and relogin ? I am only seeking a Windows Authentication solution.  

Please note: 
I am using MVC5 example.

**Comment by MohammadYounes** [comment]
This is the default browser behavior, it will cache the credentials and use them for subsequent requests, You have to close the browser to clear the credentials cache or you may try this approach: http://signinas.codeplex.com/

> related #10
