### ISSUE TITLE
Where is the definition of GetWindowsLoginInfo?

### ISSUE THREAD

**Issue by joshidp** [MohammadYounes/MVC5-MixedAuth#49]
Hi,

I have a query, where have you written definition of GetWindowsLoginInfo?

I have similar requirement where I want to get the user roles for authorisation but don't want to make LDAP call for that because it makes it slow.

Is there any better way to implement it?

Thanks,
Deepak

**Comment by MohammadYounes** [comment]
Hi,

Not sure I understand your question, Can you elaborate more ?

> Also check #1, #3 and [Importing AD Groups as Role Claims](https://github.com/MohammadYounes/MVC5-MixedAuth#importing-ad-groups-as-role-claims)

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
