### ISSUE TITLE
405.0 - Method not allowed

### ISSUE THREAD

**Issue by jon19800404** [MohammadYounes/MVC5-MixedAuth#50]
Hi,

I am using your codes to mixed authentication, copied all the required codes, web.config settings etc, but when I click on the Windows login button I get 405.0 - Method not allowed. I am suffering from this now  since 2 days, cannot find any explanation or help. Your source working perfectly, without any configuration.

EDIT1: In Firebug the _WindowsLoginPartial has the following code:

```html
<form class="form-horizontal" method="post" role="form" action="/MyWeb.Site/Windows"><input name="__RequestVerificationToken" value="2oXRYnWK8zgWw...." type="hidden">
  <input name="returnUrl" type="hidden">        
  <input id="windowsLogin" value="Windows" class="btn btn-default" type="submit">
</form>
```

I think "/MyWeb.Site/Windows" a wrong link. In your project there is a "/Login" at the end. The code that generates this link is (as your code, I don't change anything):
```c#
public static MvcForm BeginWindowsAuthForm(this HtmlHelper htmlHelper, object htmlAttributes)
{
     return htmlHelper.BeginForm("Login", "Windows", FormMethod.Post, htmlAttributes);
}
```
If I change that link in FireBug to "/MyWeb.Site/Windows/Login", then I can log in as Windows user. But where did the "/Login" go? :)

Please help.

Thx,
Jon

**Comment by MohammadYounes** [comment]
Hi,

It's hard to tell what is causing this without the modified code, Can you provide me with a copy ? 

Thanks!

**Comment by jon19800404** [comment]
Hi,

thx for the quick reply, I am able to manage to make the code working, by replacing:
`@using (Html.BeginWindowsAuthForm(new { @class = "form-horizontal", role = "form" }))`
in the _WindowsLoginPartial to:
`<form class="form-horizontal" method="post" role="form" action="@Url.Action("Login", "Windows")">`
Now its working! But still cant figure it out the strange URL that misses "/Login"

Thx for the whole solution and work!
Bests,
Jon

**Comment by MohammadYounes** [comment]
May be you are using a different version of the HTML helpers? In case you find out why, let me know!

Thanks.
