### ISSUE TITLE
Where is "MVC5-MixedAuth.mdf" database file?

### ISSUE THREAD

**Issue by developer2006** [MohammadYounes/MVC5-MixedAuth#51]
Hello Mohammad,

I just downloaded your solution ... I tried to run the application but I can not found MVC5-MixedAuth.mdf file to attach it and see your solution in action... could you please help out to generate this file?

Thanks,

**Comment by MohammadYounes** [comment]
Hello @developer2006 ,

The file is auto generated once you rung the app. If you are using IIS instead of IIS Express, change the connection string to use SQLExpress.

Thanks.
