### ISSUE TITLE
User Credentials promted keeps coming back

### ISSUE THREAD

**Issue by bartvanduinkerken** [MohammadYounes/MVC5-MixedAuth#52]
I have implemented this app locally and everything works fine. When I deploy it to a webserver I keept getting promt for user credntials. When I login I keep have to enter my credentials and getting error 401: HTTP Error 401. The requested resource requires user authentication.

I have tried adding the website to Local intranet as wel as adding it tot Trusted sites. Both give same result. Some how it is not sending my windows account credentials to the server. I know my credentials are correct for my local computer because I log in with them every day.

I have tried many of the solutions for other issues but so far no luck.

**Comment by MohammadYounes** [comment]
Correct me if I am wrong 

>  I know my credentials are correct for my local computer because I log in with them every day.

Can the web server you deployed the application on validate your credentials ? Is it on the same domain ?

**Comment by bartvanduinkerken** [comment]
Hi, 
It is not on the same domain. That is why I tried adding it to Trusted sites in Internet Options. I had it deployed in Azure(outside of domain) and it worked for a few accounts. And for some it did not

**Comment by MohammadYounes** [comment]
Are all accounts part of the web server domain ?

**Comment by bartvanduinkerken** [comment]
No all of the accounts I use to test are internal domain accounts and are not domain accounts on the Server.

**Comment by MohammadYounes** [comment]
@bartvanduinkerken The credentials can't be validated if they are not in the same domain as the web server.

**Comment by bartvanduinkerken** [comment]
Ok not even when they are added to the trusted zone in the internet options?

**Comment by MohammadYounes** [comment]
@bartvanduinkerken IIS will perform the authentication against the domain it belongs to, adding the site to the trusted zone is related to the client and makes no difference to the web server.

**Comment by bartvanduinkerken** [comment]
Hi Mohammad, thank you for the clarification. I did not know this. Thank you for all your help.
