### ISSUE TITLE
Cookie Authentication - Time out event

### ISSUE THREAD

**Issue by kamranbashir** [MohammadYounes/MVC5-MixedAuth#54]
Salam brother,
when we using app.UseCookieAuthentication, do we have in active user session time out event available in code? so i can perfom logging or any  thing on that event.

Jazak Allah Khair
Kamran

**Comment by MohammadYounes** [comment]
Salam,

I believe this is what you are looking for https://stackoverflow.com/questions/23090706/how-to-know-when-owin-cookie-will-expire 

Thanks.
