### ISSUE TITLE
Invalid Crendentials

### ISSUE THREAD

**Issue by Madhu-Patty** [MohammadYounes/MVC5-MixedAuth#55]
Hi Mohammed, 

Thanks for your code. Its working very well. 
I need to get access on windows authentication dialog box. How do i do that?
I need to display error message or delay seconds on the Invalid Credentials!

**Comment by MohammadYounes** [comment]
@Madhavi-Pathipaati I don't think it's possible to control this dialog.  However, you may try https://github.com/MohammadYounes/OWIN-MixedAuth/issues/104 to show or redirect to a custom error page.

**Comment by Madhu-Patty** [comment]
I have my code like this

public static void RegisterWindowsAuthentication(this MvcApplication app)
{
app.EndRequest += (object sender, EventArgs e) =>
{
if (app.Context.Response.StatusCode == 418)
{
app.Context.Response.Clear();
app.Context.Response.Write("user pressed cancel");

            }
            else if (app.Context.Response.StatusCode == 401)
            {
                app.Context.Response.Clear();
                app.Context.Response.Write("login failed.");
            }
        };
Global.asax has
public MvcApplication()
{
this.RegisterWindowsAuthentication();
}

Web.config has
<system.webServer>

I have my code like this

public static void RegisterWindowsAuthentication(this MvcApplication app)
{
app.EndRequest += (object sender, EventArgs e) =>
{
if (app.Context.Response.StatusCode == 418)
{
app.Context.Response.Clear();
app.Context.Response.Write("user pressed cancel");

            }
            else if (app.Context.Response.StatusCode == 401)
            {
                app.Context.Response.Clear();
                app.Context.Response.Write("login failed.");
            }
        };
Global.asax has
public MvcApplication()
{
this.RegisterWindowsAuthentication();
}

Web.config has
<system.webServer>
<httpErrors errorMode="Custom" existingResponse="Replace">
      <remove statusCode="401" subStatusCode="-1" />
      <error statusCode="401" path="/Account/Authentication" responseMode="ExecuteURL" />
    </httpErrors>
</system.webServer>
Always getting 401 and always redirecting to custom error page. Can you help me on this?



Always getting 401 and always redirecting to custom error page. Can you help me on this?

**Comment by Madhu-Patty** [comment]
@MohammadYounes 
Thank you for your response. Everything seems to be working fine expect the below one.

![image](https://user-images.githubusercontent.com/61248114/79468817-681d5f00-7fcd-11ea-9884-c4d599eef1e0.png)

Our company requirement is -
We still need to get Windows auth dialog. When user enter invalids credentials or nothing is entered and press Ok "display error message or go to error page" and press cancel should display "display error message or go to error page"

I tried as you mentioned  in #104. It always redirecting to 401 and error message and not displaying windows auth dialog box. Can you please help me on this?

I tried having Application_EndRquest like below
   protected void Application_EndRequest(object sender, EventArgs e)
        {
            if (Response.Status.Contains("401"))
            {
                Response.ClearContent();
                Response.WriteFile("~/Views/Authentication/InvalidUser.cshtml");
                Response.ContentType = "text/html";
            }
        }

**Comment by MohammadYounes** [comment]
@Madhu-Patty If you are writing a custom response in `Global.asax` then remove the custom http errors from web.config.

**Comment by Madhu-Patty** [comment]
Thanks for your response. I tried that way as well. Its always going to 401. I mean with valid or invalid credentials

**Comment by MohammadYounes** [comment]
@Madhu-Patty Can you share a sample project to trace this ?

**Comment by Madhu-Patty** [comment]
I added only this code in global.asax. Rest of the code is same. I got it from your MixedAuth only

![image](https://user-images.githubusercontent.com/61248114/80320372-11413200-87e4-11ea-8b0b-d63389f89724.png)

Please launch your application on firefox and click on the Windows, don't enter any credentials and click on ok button, 1st time got 401 and redirect to contact page. After sometime clickon windows again and don't enter anything and click on Ok 2nd time also got 401 and redirect to Contact page.

3rd time same procedure - instead of getting 401(login failed),  its going to User Pressed Cancel (418). Do you know why?

![image](https://user-images.githubusercontent.com/61248114/80320418-48afde80-87e4-11ea-9072-a0434a42c382.png)


**Our requirement**

We need to add delay timer - 1st time click on Windows dialog Ok button with Invalid credentials - Display delay timer with 2 secs and 2nd time click on Windows dialog Ok button with Invalid credentials, display delay timer with 4 secs. Each time entering Invalid Credentials, twice the previous time. Maximum display 5 times when Invalid credentials are entered. For the 3rd time Its going to **'User Pressed Cancel'**
